# -*- coding: utf-8 -*-
"""Energy Balance Test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDja-rkiLmHnHnRFO9tyJvrmv-NAjyzR
"""

def energy_balance(Qi, Qsw, Qlw, Qh, Qe, Qr, Qmelt):
  # This program should execute the several shorter programs for the energy balance